### ISSUE TITLE
Issues with request options handling and events

### ISSUE THREAD

**Issue by elazar** [WyriHaximus/ReactGuzzle#5]
`\WyriHaximus\React\Guzzle\HttpClientAdapter` [implements `\GuzzleHttp\Adapter\AdapterInterface`](https://github.com/WyriHaximus/ReactGuzzle/blob/f03be27faee021ab39947fa677ef8b35e4c5ac66/src/HttpClientAdapter.php#L27). However, its `send()` method implementation has an incompatibility with that of `AdapterInterface`: it [includes an `$options` parameter](https://github.com/WyriHaximus/ReactGuzzle/blob/f03be27faee021ab39947fa677ef8b35e4c5ac66/src/HttpClientAdapter.php#L134) that [`AdapterInterface` does not](https://github.com/guzzle/guzzle/blob/40db53833aaea528347994acd4578d7b9b2211ee/src/Adapter/AdapterInterface.php#L22).

Request methods in `\GuzzleHttp\Client`, such as `get()`, [call its `createRequest()` method](https://github.com/guzzle/guzzle/blob/40db53833aaea528347994acd4578d7b9b2211ee/src/Client.php#L145), which [handles creating a request object](https://github.com/guzzle/guzzle/blob/40db53833aaea528347994acd4578d7b9b2211ee/src/Client.php#L137) that includes the options passed in the call to the request method (i.e. `get()`). `send()` is then called and passed that request object, which [leaves it to the adapter](https://github.com/guzzle/guzzle/blob/40db53833aaea528347994acd4578d7b9b2211ee/src/Client.php#L182) to handle request options and events. You can see an example of this in the `send()` implementation of `\GuzzleHttp\Adapter\Curl\CurlAdapter`, which [calls `RequestEvents::emitBefore()`](https://github.com/guzzle/guzzle/blob/40db53833aaea528347994acd4578d7b9b2211ee/src/Adapter/Curl/CurlAdapter.php#L74) and other similar methods that trigger events, in particular those listened for by plugins such as the [Oauth plugin](https://github.com/guzzle/oauth-subscriber). Lack of equivalent calls in the `send()` method of `\WyriHaximus\React\Guzzle\HttpClientAdapter` currently prevents plugins from working when it's used.

**Comment by elazar** [comment]
This appears to be working. I've got the Twitter plugin able to communicate with the Twitter API. Thanks!

**Comment by WyriHaximus** [comment]
Awesome :+1:
